version: "3.9"

services:
  backend:
    container_name: embedchain_backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    container_name: embedchain_frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
